In [2]:
import numpy as np

# Librería Numpy

<p style="background-color:lightpink; padding:1em"><b>Ejercicio 1</b><br/>
    Defina las siguientes matrices: <br/>
    $A=\begin{bmatrix}
    3 & 2 & 1\\
    2 & 1 & 3
    \end{bmatrix}
    B=\begin{bmatrix}
    3 & 0 & 0\\
    0 & 3 & 0\\
    0 & 0 & 3
    \end{bmatrix}
    C=\begin{bmatrix}
    1 & 0 & 4 & 6 & 3 & 4
    \end{bmatrix}$ 
</p>

In [3]:
A = np.array([[3, 2, 1],
              [2, 1, 3]])

B = np.array([[3, 0, 0],
              [0, 3, 0],
              [0, 0, 3]])

C = np.array([1, 0, 4, 6, 3, 4])

print(A)
print(B)
print(C)

[[3 2 1]
 [2 1 3]]
[[3 0 0]
 [0 3 0]
 [0 0 3]]
[1 0 4 6 3 4]


<p style="background-color:lightpink; padding:1em"><b>Ejercicio 2</b><br/>
    Asigne las variables a los valores contenidos en las matrices de la siguiente manera: <br/>
    <code>a02</code>=$A(0,2)$<br/>
    <code>b11</code>=$B(1,1)$<br/>
    <code>c3</code>=$C(3)$<br/>
    <code>b0</code>=primera columna de $B$<br/>
    <code>cpar</code>=todos los elementos en posiciones pares de $C$
</p>

In [4]:
a02 = A[0,2]
b11 = B[1,1]
c3 = C[3]
b0 = B[:,0]
cpar = C[::2]

print(a02)
print(b11)
print(c3)
print(b0)
print(cpar)

1
3
6
[3 0 0]
[1 4 3]


<p style="background-color:lightpink; padding:1em"><b>Ejercicio 3</b><br/>
    Defina el siguiente vector y multiplique sus valores por 10: <br/>
    $
    L=\begin{bmatrix}
    0.3 & -0.1 & 0.2 & 0.7 & -0.3 & 0.1
    \end{bmatrix}$ <br/>
    $L_{10} = 10\cdot L$
</p>

In [5]:
L = np.array([0.3, -0.1, 0.2, 0.7, -0.3, 0.1])
L10 = 10*L

print(L)
print(L10)

[ 0.3 -0.1  0.2  0.7 -0.3  0.1]
[ 3. -1.  2.  7. -3.  1.]


<p style="background-color:lightpink; padding:1em"><b>Ejercicio 4</b><br/>
    Defina la siguiente matriz y realice la operación indicada: <br/>
    $
    M=\begin{bmatrix}
    2 & 1 \\
    3 & 2 
    \end{bmatrix}$ <br/>
    $M_p = M \cdot M^T$
</p>

In [6]:
M = np.array([[2, 1],
              [3, 2]])

Mp = M @ M.T

print(M)
print(Mp)

[[2 1]
 [3 2]]
[[ 5  8]
 [ 8 13]]


<p style="background-color:lightpink; padding:1em"><b>Ejercicio 5</b><br/>
    Genere una matriz de 4x2 con valores aleatorios
</p>

In [7]:
np.random.randn(4,2)

array([[ 0.19352372,  0.37136295],
       [ 0.97150147, -2.08271216],
       [-2.90234174, -0.06999893],
       [-0.73299989, -0.16796516]])

<p style="background-color:lightpink; padding:1em"><b>Ejercicio 6</b><br/>
    Defina una secuencia de números entre -10 y 10 con separación de 2
</p>

In [8]:
np.arange(-10, 10, 2)

array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8])

<p style="background-color:lightpink; padding:1em"><b>Ejercicio 7</b><br/>
    Defina una función de Python que tome a su entrada un array y devuelva un array sólo con los elementos en posiciones impares, elevados al cuadrado.<br/>
    La cabecera de la función es la siguiente:<br/>
    <code>def funcion_ejercicio(array_entrada):</code><br/>
</p>

In [11]:
def funcion_ejercicio(array_entrada):
    elementos_pares = array_entrada[::1]
    return np.power(elementos_pares, 2)

funcion_ejercicio(np.array([0, 1, 2, 3, 4, 5, 6]))

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)